# coding=UTF-8
from datetime import timedelta


JSON_AS_ASCII = True
USE_X_SENDFILE = False
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_PATH = None
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_NAME = "session"
MAX_COOKIE_SIZE = 4093
SESSION_COOKIE_SAMESITE = None
PROPAGATE_EXCEPTIONS = None
ENV = "production"
DEBUG = True
SECRET_KEY = None
EXPLAIN_TEMPLATE_LOADING = False
MAX_CONTENT_LENGTH = None
APPLICATION_ROOT = "/"
SERVER_NAME = None
PREFERRED_URL_SCHEME = "http"
JSONIFY_PRETTYPRINT_REGULAR = False
TESTING = False
PERMANENT_SESSION_LIFETIME = timedelta(31)
TEMPLATES_AUTO_RELOAD = None
TRAP_BAD_REQUEST_ERRORS = None
JSON_SORT_KEYS = True
JSONIFY_MIMETYPE = "application/json"
SESSION_COOKIE_HTTPONLY = True
SEND_FILE_MAX_AGE_DEFAULT = timedelta(0, 43200)
PRESERVE_CONTEXT_ON_EXCEPTION = None
SESSION_REFRESH_EACH_REQUEST = True
TRAP_HTTP_EXCEPTIONS = False
CACHE_CONFIG = {
    'CACHE_TYPE': 'filesystem',
    'CACHE_DIR': '/tmp/cache',
    'CACHE_DEFAULT_TIMEOUT': 0
}
